### ISSUE TITLE
Can't connect account to the dapp

### ISSUE THREAD

**Issue by anaelleltd** [ImbueNetwork/dapp#62]
Hello,

I have tried to log into the dapp to make a transfer, but the dapp doesn't respond when I click to select my account.
I still went ahead, entered a number in the KSM field and clicked "transfer funds". A message then popped up to say there is "no account connected", yet the dapp status switched to "transfering...". 

Please look into this issue.

Thanks.
Anaelle LTD.

**Comment by samelamin** [comment]
thanks, @anaelleltd , I am not sure what could have caused this but we can easily disable the transfer button until after a user has signed in!

In the meantime, feel free to try a different browser with polkadotjs installed. We are working on supporting more wallets

**Comment by samelamin** [comment]
Fixed on https://github.com/ImbueNetwork/dapp/pull/63
