### ISSUE TITLE
knex package fails to install

### ISSUE THREAD

**Issue by simrat12** [ImbueNetwork/dapp#69]
Hey, I have cloned the repo and the API container fails to run due to the knex package not being present. I have added commands to the dockerfile in order to install this package and add to Path, but the issue persists. Below, is the dockerfile along with the error message shown in the terminal.

![image](https://user-images.githubusercontent.com/68758432/213820446-0151db08-5b21-48dd-91fe-a6046ac11f13.png)

**Comment by f-gate** [comment]
have spoken with simrat marking as closed
