### ISSUE TITLE
Unable to run locally on Windows

### ISSUE THREAD

**Issue by simrat12** [ImbueNetwork/dapp#71]
I am trying to run locally on windows but unable to do so - error displayed below:
![image](https://user-images.githubusercontent.com/68758432/214031045-04aff2e3-7b8f-43cb-8632-fac1a65893ee.png)
I have then changed the start command on the package.json as shown below, which runs successfully but unable to find localhost:
"start": "set NODE_ENV=development && set TS_NODE_PROJECT=./src/backend/tsconfig.json && webpack watch --config ./src/frontend/webpack.config.js --mode development & webpack watch --config ./src/legacy/webpack.config.js --mode development & nodemon -L --watch src/backend --ext 'js,ts' --exec 'node --inspect=0.0.0.0:9229 --require ts-node/register src/backend/index.ts'"

![image](https://user-images.githubusercontent.com/68758432/214031964-105da916-64f7-4e9a-b495-fac396e57b0d.png)

**Comment by samelamin** [comment]
@beyond-code-github are you able to help @simrat12 with getting his OS working. The build works fine since its passing on CI

**Comment by f-gate** [comment]
@simrat12 Can you put in a PR with how you did it in the end? 

Then we can close this issue

**Comment by f-gate** [comment]
https://github.com/ImbueNetwork/dapp/pull/78
